from datasets import Dataset

data = {
    "question": [
        "What is the English name of the program?",
        "What is the abbreviation for the degree in English?",
        "How many credits are required for graduation?",
        "What is the medium of instruction?",
        "Which institute gives the degree to graduates?",
        "When did the program start its first semester?",
        "Is the program an academic or advanced academic bachelor's degree?",
        "What is a possible career path regarding AI?",
        "What is a possible career path regarding mechanical systems?",
        "What is a possible career path regarding management?",
        "Who is an instructor responsible for the program with a focus on Electrical Engineering?",
        "Where is the location of study?",
        "What national plan does the program align with?",
        "What is the mission of the Institute mentioned in the document?",
        "What are the 21st-century skills the curriculum aims to cultivate?",
        "What is the 'next S-curve' industry mentioned in the importance of the program?",
        "What does 'PEO' stand for in the context of the program?",
        "What is Program Educational Objective (a)?",
        "What is Program Educational Objective (e)?",
        "How many weeks are in a standard academic semester?",
        "When is the summer course typically held?",
        "What is the minimum high-school requirement for applicants?",
        "What English proficiency tests are accepted for non-native speakers?",
        "What is a common issue for new students mentioned in the doc?",
        "How many 1st year students were planned for the 2020 academic year?",
        "What is the estimated expenditure per person for producing a scholar per year?",
        "Can credits be transferred from other institutions?",
        "What is the GPA requirement for guaranteed admission to the integrated Master program?",
        "What is the focus of the first-year projects?",
        "What do students learn in the third year regarding trending areas?",
        "What is the credit weight for General Education?",
        "How many credits are assigned to the RAI Engineering Capstone Design?",
        "What does the first and second digit of the subject code '01' mean?",
        "What does the third and fourth digit '41' mean in the subject code?",
        "What is the course code for 'Professional Ethics'?",
        "How many credits is the 'Academic Listening and Speaking' course?",
        "What is the prerequisite for 'Advanced Calculus'?",
        "What topics are covered in 'General Physics 1'?",
        "What is the credit structure (L-E-S) for 'Computer Programming for RAI'?",
        "Which course covers 'Kinematics and Dynamics'?",
        "What is the minimum duration for the internship requirement?",
        "What alternative study option allows a 16-week internship?",
        "What is the objective of the 'RAI Engineering Capstone Design Preparation'?",
        "Which course introduces 'Artificial Intelligence Technology'?",
        "What is the focus of 'Robotics Laboratory 2'?",
        "What does 'L' stand for in the credit notation (L-E-S)?",
        "What does 'E' stand for in the credit notation (L-E-S)?",
        "What does 'S' stand for in the credit notation (L-E-S)?",
        "What is the required student attendance percentage for evaluation?",
        "How often is the curriculum updated?"
    ],
    "answer": ["" for _ in range(50)],
    "contexts": [
        ["Bachelor of Engineering Program in Robotics and AI Engineering (International Program)[cite: 4, 5, 6]."],
        ["B.Eng. (Robotics and AI Engineering) [cite: 38, 44]."],
        ["At least 131 credits[cite: 41, 46, 285, 304, 513, 1039]."],
        ["English[cite: 56, 57]."],
        ["King Mongkut's Institute of Technology Ladkrabang[cite: 29, 63, 100]."],
        ["Semester 1 of academic year 2018 (August 2018)[cite: 67]."],
        ["Academic bachelor's degree program[cite: 50, 51, 52]."],
        ["Software Architect for AI or Expert Systems Analyst[cite: 77, 79]."],
        ["Software Engineer for Mechatronics and Machines or Machine Designer[cite: 73, 78]."],
        ["Technology Manager for Robotics and AI[cite: 80]."],
        ["Dr. Poom Konghuayrob or Dr. Kanoknuch Songsuwankit[cite: 83, 84, 521, 524]."],
        ["King Mongkut's Institute of Technology Ladkrabang[cite: 99, 100]."],
        ["National Economic and Social Development Plan (2017-2021)[cite: 102, 115]."],
        ["Master of Innovation and the Corner Stone of Fundamental[cite: 120]."],
        ["Creativity, critical-thinking, communication, and collaboration[cite: 141]."],
        ["Digital industry including IoT, Cloud, Robotics, and AI[cite: 148]."],
        ["Program Educational Objectives[cite: 152]."],
        ["Engineering Quality: apply engineering practice to solve significant problems[cite: 153, 154]."],
        ["Lifelong Learning: learn new technologies to respond to a changing environment[cite: 153, 159]."],
        ["Not less than 15 weeks (excluding examination weeks)[cite: 225]."],
        ["June - July[cite: 232, 237, 569]."],
        ["Complete high-school education or equivalent[cite: 242, 243]."],
        ["TOEFL or IELTS[cite: 246]."],
        ["Adjusting to social settings and campus lifestyles with greater freedom[cite: 252, 253]."],
        ["60 students[cite: 265, 266]."],
        ["Average of 194,613 baht/person/year[cite: 270]."],
        ["Yes, with consent of the executive program committee[cite: 230, 274]."],
        ["Overall GPA of at least 3.00[cite: 279]."],
        ["Hands-on experience and basic development of robotics technologies[cite: 291]."],
        ["Machine perception, cognition and reasoning, and IoT[cite: 294, 295]."],
        ["30 credits[cite: 307, 338, 1039]."],
        ["3 credits[cite: 358, 502, 587]."],
        ["Faculty of Engineering[cite: 321, 322, 323]."],
        ["Robotics and AI program[cite: 324, 325, 326]."],
        ["01006502[cite: 340, 1280]."],
        ["3 (3-0-6) credits[cite: 340, 1256]."],
        ["01006710 Introduction to Calculus[cite: 351, 1508]."],
        ["Motion, space/time, kinematics, Newton's laws, energy, and momentum[cite: 351, 1515]."],
        ["3 (2-2-5)[cite: 351, 407, 1597]."],
        ["01416308[cite: 351, 417, 1567]."],
        ["At least 8 weeks[cite: 555, 556, 573]."],
        ["Co-Operative Education[cite: 555, 559, 570, 573]."],
        ["Instruct and prepare students in effective technical oral presentations[cite: 358, 460, 1648]."],
        ["01416305[cite: 351, 417, 1558]."],
        ["Understanding the mobile robot through instructive experiments[cite: 352, 1632, 1635]."],
        ["Lecture or Learning hours[cite: 398, 399, 400]."],
        ["Laboratory hours[cite: 398, 399, 400]."],
        ["Self-study hours[cite: 398, 399, 400]."],
        ["At least 80%[cite: 604, 1133]."],
        ["Updated at least every 5 years[cite: 1061, 1070]."]
    ],
    "ground_truth": [
        "Bachelor of Engineering Program in Robotics and AI Engineering (International Program)[cite: 4, 5, 6].",
        "B.Eng. (Robotics and AI Engineering) [cite: 38, 44].",
        "At least 131 credits[cite: 41, 46, 285, 304, 513, 1039].",
        "English[cite: 56, 57].",
        "King Mongkut's Institute of Technology Ladkrabang[cite: 29, 63, 100].",
        "Semester 1 of academic year 2018[cite: 67].",
        "Academic bachelor's degree program[cite: 50, 51, 52].",
        "Software Architect for AI[cite: 79].",
        "Software Engineer for Mechatronics and Machines[cite: 73].",
        "Technology Manager for Robotics and AI[cite: 80].",
        "Dr. Poom Konghuayrob[cite: 83, 84].",
        "King Mongkut's Institute of Technology Ladkrabang[cite: 99, 100].",
        "National Economic and Social Development Plan (2017-2021)[cite: 102, 115].",
        "Master of Innovation and the Corner Stone of Fundamental[cite: 120].",
        "Creativity, critical-thinking, communication, and collaboration[cite: 141].",
        "Digital industry (IoT, Cloud, Robotics, AI)[cite: 148].",
        "Program Educational Objectives[cite: 152].",
        "Apply engineering practice to solve significant problems[cite: 153, 154].",
        "Learn new technologies to respond to a changing environment[cite: 153, 159].",
        "Not less than 15 weeks[cite: 225].",
        "June - July[cite: 232, 237, 569].",
        "Complete high-school education or equivalent[cite: 242, 243].",
        "TOEFL or IELTS[cite: 246].",
        "Adjusting to social settings and campus lifestyles[cite: 252, 253].",
        "60 students[cite: 265, 266].",
        "194,613 baht/person/year[cite: 270].",
        "Yes, with consent of the committee[cite: 230, 274].",
        "At least 3.00[cite: 279].",
        "Hands-on experience and basic robotics development[cite: 291].",
        "Machine perception, cognition, reasoning, and IoT[cite: 294, 295].",
        "30 credits[cite: 307, 338, 1039].",
        "3 credits[cite: 358, 502, 587].",
        "Faculty of Engineering[cite: 321, 322, 323].",
        "Robotics and AI program[cite: 324, 325, 326].",
        "01006502[cite: 340, 1280].",
        "3 (3-0-6) credits[cite: 340, 1256].",
        "01006710 Introduction to Calculus[cite: 351, 1508].",
        "Motion, kinematics, Newton's laws, energy, and momentum[cite: 351, 1515].",
        "3 (2-2-5)[cite: 351, 407, 1597].",
        "01416308[cite: 351, 417, 1567].",
        "At least 8 weeks[cite: 555, 556, 573].",
        "Co-Operative Education[cite: 555, 559, 570, 573].",
        "Prepare students in effective technical oral presentations[cite: 358, 460, 1648].",
        "01416305[cite: 351, 417, 1558].",
        "Understanding mobile robots through experiments[cite: 352, 1632, 1635].",
        "Lecture or Learning hours[cite: 398, 399, 400].",
        "Laboratory hours[cite: 398, 399, 400].",
        "Self-study hours[cite: 398, 399, 400].",
        "At least 80%[cite: 604, 1133].",
        "Updated at least every 5 years[cite: 1061, 1070]."
    ]
}

dataset = Dataset.from_dict(data)
#save dataset to file
dataset.save_to_disk("./temp_dataset")